# Generated by Django 2.2.2 on 2019-06-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_tempproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempProduct',
        ),
    ]
