# Generated by Django 2.2.2 on 2019-06-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tempproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
