# Generated by Django 2.2.2 on 2019-06-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tempproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='TempProduct',
        ),
    ]
