# Generated by Django 2.2.2 on 2019-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190615_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempproduct',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
    ]
