# Generated by Django 2.2.2 on 2019-06-15 18:15

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCCESING', 'В обработке'), ('SHIPMENT', 'Отправлен'), ('CLOSED', 'Закрыт')], default=order.models.Status('В обработке'), max_length=20),
        ),
    ]
