# Generated by Django 2.2.2 on 2019-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190615_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'PROCCESING'), ('Отправлен', 'SHIPMENT'), ('Закрыт', 'CLOSED')], default='В обработке', max_length=20),
        ),
    ]
